name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *' # Daily. Ref https://crontab.guru/examples.html

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Build
      run: npm install
    - name: Scrape
      run: npm run scrape
      # env:
      #   WHATEVER_TOKEN: ${{ secrets.YOU_WANT }}
    - name: Commit and push
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date +"%Y-%m-%d %T")
        git commit -m "Scrape on ${timestamp}" || exit 0
        git push